workflows:
  ios-release:
    name: iOS Release Build
    environment:
      groups:
        - ios_credentials
      vars:
        FIREBASE_APP_ID: "1-563950462964-ios-a42d70b510fffff032bba1"
        FIREBASE_PROJECT_ID: "clubnotification-c0a25"
        GOOGLE_APPLICATION_CREDENTIALS_JSON: Encrypted(GOOGLE_APPLICATION_CREDENTIALS_JSON)

    scripts:
      # 1. تثبيت Firebase CLI
      - name: Install Firebase CLI
        script: |
          curl -sL https://firebase.tools | bash

      # 2. تثبيت dependencies الخاصة بـ Flutter
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      # 3. التحقق من قدرات iOS
      - name: Verify iOS Capabilities
        script: |
          echo "Checking Push Notifications capability..."
          if ! plutil -p ios/Runner/Info.plist | grep -q "aps-environment"; then
            echo "⚠️ Push Notifications capability not set in Info.plist"
            exit 1
          fi
          echo "✅ Push Notifications capability found"

          echo "Checking Background Modes (remote-notification)..."
          if ! plutil -p ios/Runner/Info.plist | grep -q "remote-notification"; then
            echo "⚠️ Background Modes (remote-notification) not set"
            exit 1
          fi
          echo "✅ Background Modes capability found"

      # 4. بناء IPA نسخة release
      - name: Build IPA
        script: |
          flutter build ipa --release
          IPA_PATH="build/ios/ipa/Runner.ipa"
          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ IPA file not found at $IPA_PATH"
            exit 1
          fi
          echo "✅ IPA built at $IPA_PATH"

      # 5. رفع التطبيق إلى Firebase App Distribution
      - name: Upload to Firebase App Distribution
        script: |
          echo "Setting up Firebase Service Account..."
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service-account.json"

          echo "Uploading IPA to Firebase App Distribution..."
          firebase appdistribution:distribute "$IPA_PATH" \
            --app "$FIREBASE_APP_ID" \
            --project "$FIREBASE_PROJECT_ID" \
            --release-notes "iOS Test Release" \
            --groups "clubIos"
