#workflows:
#  ios-release:
#    name: iOS Release Build
#    max_build_duration: 60
#    environment:
#      flutter: stable
#
#      vars:
#        FIREBASE_APP_ID: "1:563950462964:ios:a42d70b510fffff032bba1"
#        FIREBASE_PROJECT_ID: "clubnotification-c0a25"
#        GOOGLE_APPLICATION_CREDENTIALS_JSON: $GOOGLE_APPLICATION_CREDENTIALS_JSON
#        APNS_KEY_ID: HNV4V35QT3
#        APNS_TEAM_ID: M7Y6M3HA47
#        APNS_AUTH_KEY_PATH: ios/certs/AuthKey_HNV4V35QT3.p8
#        IOS_PROVISIONING_PROFILE_PATH: ios/certs/ClubAppProfile.mobileprovision
#        P12_PATH: ios/certs/ios_distribution.p12
#        P12_PASSWORD: $P12_PASSWORD
#
#    cache:
#      cache_paths:
#        - $HOME/.pub-cache
#        - ios/Pods
#        - $HOME/Library/Caches/CocoaPods
#        - $FLUTTER_ROOT/bin/cache
#        - build/
#
#    scripts:
#      # 1. تثبيت Firebase CLI إذا لم يكن موجود
#      - name: Install Firebase CLI
#        script: |
#          if ! command -v firebase &> /dev/null; then
#            echo "Installing Firebase CLI..."
#            curl -sL https://firebase.tools | bash
#          fi
#          echo "✅ Firebase CLI installed"
#
#      # 2. تثبيت Flutter dependencies
#      - name: Install Flutter dependencies
#        script: |
#          flutter pub get
#          echo "✅ Flutter dependencies installed"
#
#      # 3. تثبيت iOS Pods
#      - name: Install iOS Pods
#        script: |
#          cd ios
#          pod install --repo-update
#          cd ..
#          echo "✅ iOS Pods installed"
#
#      # 4. إعداد APNs Auth Key
#      - name: Configure APNs Auth Key
#        script: |
#          mkdir -p "$CM_BUILD_DIR/private_keys"
#          cp "$APNS_AUTH_KEY_PATH" "$CM_BUILD_DIR/private_keys/AuthKey.p8"
#          if [ ! -f "$CM_BUILD_DIR/private_keys/AuthKey.p8" ]; then
#            echo "❌ Failed to copy APNs Auth Key"
#            exit 1
#          fi
#          echo "✅ APNs Auth Key configured at $CM_BUILD_DIR/private_keys/AuthKey.p8"
#
#      # 5. استيراد P12 إلى Keychain
#      - name: Import P12 Certificate to Keychain
#        script: |
#          echo "Creating temporary Keychain..."
#          security create-keychain -p "" "$CM_BUILD_DIR/build.keychain"
#
#          # تأكد من وجود مجلد build
#          mkdir -p "$CM_BUILD_DIR/build"
#
#          echo "Decrypting P12 from path: $P12_PATH ..."
#          openssl pkcs12 -in "$P12_PATH" -out "$CM_BUILD_DIR/build/push.pem" -nodes -passin pass:Mo-12345
#          if [ ! -f "$CM_BUILD_DIR/build/push.pem" ]; then
#            echo "❌ Failed to decrypt P12"
#            exit 1
#          fi
#          echo "✅ P12 decrypted at $CM_BUILD_DIR/build/push.pem"
#
#          echo "Importing PEM into Keychain..."
#          security import "$CM_BUILD_DIR/build/push.pem" -k "$CM_BUILD_DIR/build.keychain" -T /usr/bin/codesign
#          security list-keychain -s "$CM_BUILD_DIR/build.keychain"
#          echo "✅ P12 imported successfully"
#
#
#      # 6. التحقق من iOS capabilities
#      - name: Verify iOS Capabilities
#        script: |
#          echo "Checking iOS capabilities..."
#          if ! plutil -p ios/Runner/Info.plist | grep -q "aps-environment"; then
#            echo "❌ aps-environment not set in Info.plist"
#            exit 1
#          fi
#          if ! plutil -p ios/Runner/Info.plist | grep -q "remote-notification"; then
#            echo "❌ Background Modes not set"
#            exit 1
#          fi
#          if ! plutil -p ios/Runner/Runner.entitlements | grep -q "aps-environment"; then
#            echo "❌ aps-environment not set in Runner.entitlements"
#            exit 1
#          fi
#          echo "✅ iOS capabilities verified"
#
#      # 7. Build IPA
#      - name: Build IPA
#        script: |
#          flutter build ipa --release
#          IPA_PATH="build/ios/ipa/Runner.ipa"
#          if [ ! -f "$IPA_PATH" ]; then
#            echo "❌ IPA file not found: $IPA_PATH"
#            exit 1
#          fi
#          echo "✅ IPA built successfully at $IPA_PATH"
#
#      # 8. Upload IPA to Firebase App Distribution
#      - name: Upload to Firebase App Distribution
#        script: |
#          echo "Writing service-account.json to $CM_BUILD_DIR ..."
#          printf "%s" "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > "$CM_BUILD_DIR/service-account.json"
#          export GOOGLE_APPLICATION_CREDENTIALS="$CM_BUILD_DIR/service-account.json"
#
#          IPA_PATH="build/ios/ipa/Runner.ipa"
#          echo "Uploading IPA to Firebase App Distribution..."
#          firebase appdistribution:distribute "$IPA_PATH" \
#            --app "$FIREBASE_APP_ID" \
#            --project "$FIREBASE_PROJECT_ID" \
#            --release-notes "iOS Test Release" \
#            --groups "clubIos"
#
#          rm "$CM_BUILD_DIR/service-account.json"
#          echo "✅ IPA uploaded successfully"
#
#
#    publishing:
#      email:
#        recipients:
#          - "muhammad.adel.abualhaijaa@gmail.com"
#
